FontInfo
{
    // Force GorDIN to always use freetype2.
    "GorDIN" "freetype2"
    "GorDIN-Black" "freetype2"
    "GorDIN-Bold" "freetype2"
    "GorDIN-Light" "freetype2"
    "GorDIN-Regular" "freetype2"
    "GorDIN-Semibold" "freetype2"
    "GorDIN Black" "freetype2"
    "GorDIN Bold" "freetype2"
    "GorDIN Light" "freetype2"
    "GorDIN Regular" "freetype2"
    "GorDIN Semibold" "freetype2"

}
